# Terminologies in statistics

## Population

- Before gathering data, we first consider the scope of our study by identifying the population. The population consists of all subjects/animals/specimens/plants, and so on, of interest.

- Examples:
	- All pine trees in Baitadi
	- All people in Nepal with the height above 155 cm
	
## Sample

- Typically, we are unable to observe the entire population; therefore, we must be content with gathering data from a subset of the population, a sample of size _n_. From this sample we make inference about the population as a whole.

- Note the difference between biological meaning of individual sample and the same term used in statistics.

- Better to use specimen for biological notation.

## Samping methods

### Simple random sampling

A simple random sample of n items is a sample in which (a) every number of the population has the same chance of being included in the sample, and (b) the members of the sample are chosen independently of each other. [Requirement (b) means that the chance of a given member of the population being chosen does not depend on which other members are chosen.]

### Sample selection from an agricultural field by simple random sampling

### Probability proportional to size sampling

### Stratified random sampling

- 

### Systematic sampling

### Cluster sampling

- 

### Multistage sampling

## Sampling error